@startuml
start

:set option to output on the standard error stream stderr;
:set option nounset, which causes the shell to indicate an error
when it encounters an undefined variable;
:set option pipefail to abort the whole script
in case of an error of one line;

:safe global Dockerfile variable WORKDIR
into variable REDMINE_WORK_DIR;
:safe string "${WORKDIR}/defaultPlugins"
into variable DEFAULT_PLUGIN_DIRECTORY;
:safe string /var/tmp/redmine/plugins/migration4.2.3.4
into variable MIGRATION4234_TMP_DIR;

if (the script is actively executed) then (yes)
:call function run_preupgrade() with all params;
else (no)
 stop
endif

:First param into variable FROM_VERSION;
:Second param into variable TO_VERSION;
:execute echo with string:
"Executing Redmine pre-upgrade from ${FROM_VERSION} to ${TO_VERSION}";

if (FROM_VERSION is equal to TO_VERSION) then (yes)
:execute echo with string:
"FROM and TO versions are the same; Exiting...";
:exit with status code 1;
end
else (no)
:execute echo with string:
"Set registry flag so startup script waits for post-upgrade to finish...";
:execute command: doguctl state "upgrading";
endif

if (is FROM_VERSION less or equal than "4.2.3-4") then (no)
    elseif (is FROM_VERSION NOT less or equal then "4.2.2-1") then (yes)
    :move plugins into a newly made directory
    with the path from the MIGRATION4234_TMP_DIR variable;
   else (no)
endif

:execute command:
doguctl config "startup/setup_done" "true";
:execute echo with string:
"Redmine pre-upgrade done";
stop

@enduml
