@startuml

start

if (is script sourced) then (yes)
    stop
else (no)
    :call function run_postupgrade() with all params;
endif


:receive postgresql DATABASE_USER,
DATABASE_USER_PASSWORD and DATABASE_DB via
doguctl command;


if (FROM_VERSION is equal to TO_VERSION) then (yes)
    stop
else (no)
endif

if (is FROM_VERSION less or equal than "4.1.0-3") then (yes)
:delete duplicated settings in database;
else (no)
endif

if (is FROM_VERSION less or equal than "4.2.3-4") then (no)
    elseif (is FROM_VERSION NOT less or equal then "4.2.2-1") then (yes)
        :migrate plugin back to plugins directory
        with the path from the MIGRATION_VERSION_4234_TMP_DIR variable;
    else (no)
endif

:render templates and update plugins

:execute command: doguctl state "upgrade done";

end

@enduml
