@startuml
start

if (is script sourced) then (yes)
    stop
else (no)
    :call function run_preupgrade() with all params;
endif

if (FROM_VERSION is equal to TO_VERSION) then (yes)
    stop
else (no)
    :execute command: doguctl state "upgrading";
endif

if (is FROM_VERSION less or equal than "4.2.3-4") then (no)
    elseif (FROM_VERSION is greater than "4.2.2-1") then (yes)
    :move plugins into a newly made directory
    with the path from the MIGRATION_VERSION_4234_TMP_DIR variable;
   else (no)
endif

:execute command: doguctl config "startup/setup_done" "true";
end

@enduml
